- id: '1734040819255'
  alias: Announce Washer is Done
  description: Announce on all Homepods when the washer is done
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.washer_run_completed
    to: 'on'
  conditions:
  - or:
    - condition: zone
      entity_id: person.john
      zone: zone.home
    - condition: zone
      entity_id: person.kelly_barbieri
      zone: zone.home
  actions:
  - action: tts.speak
    metadata: {}
    data:
      cache: true
      media_player_entity_id: media_player.all_pods
      message: Hi there humans! Your washing is done, now its time for the dryer
    target:
      entity_id: tts.home_assistant_cloud
  mode: single
- id: '1734040890462'
  alias: Announce Dryer is Done
  description: Announce on all Homepods when the dryer is done
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.dryer_run_completed
    to: 'on'
  conditions:
  - or:
    - condition: zone
      entity_id: person.john
      zone: zone.home
    - condition: zone
      entity_id: person.kelly_barbieri
      zone: zone.home
  actions:
  - action: tts.speak
    metadata: {}
    data:
      cache: true
      media_player_entity_id: media_player.all_pods
      message: 'Hi there humans! Your dryer is done, grab those clothes while still
        hot... And DO NOT forget to clean the lint filter Kelly '
    target:
      entity_id: tts.home_assistant_cloud
  mode: single
- id: '1735344088242'
  alias: Master Bedroom CO2 Alerting
  description: Master Bedroom CO2 Alerting
  triggers:
  - trigger: state
    entity_id:
    - sensor.bedroom_multisensor_co2
  conditions:
  - condition: or
    conditions:
    - condition: state
      entity_id: person.john
      state: home
    - condition: state
      entity_id: person.kelly_barbieri
      state: home
  actions:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.bedroom_multisensor_co2
        above: 550
        below: 750
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 37
          - 162
          - 58
          brightness_pct: 25
        target:
          entity_id: light.bedroom_multisensor_rgb_light
    - conditions:
      - condition: numeric_state
        entity_id: sensor.bedroom_multisensor_co2
        above: 750
        below: 1000
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 255
          - 123
          - 0
          brightness_pct: 25
        target:
          entity_id: light.bedroom_multisensor_rgb_light
    - conditions:
      - condition: numeric_state
        entity_id: sensor.bedroom_multisensor_co2
        above: 1000
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 255
          - 0
          - 0
          brightness_pct: 100
          flash: long
        target:
          entity_id: light.bedroom_multisensor_rgb_light
      - action: tts.speak
        metadata: {}
        data:
          cache: true
          media_player_entity_id: media_player.master_bedroom
          message: Warning! The CO2 Level in the Master Bedroom is dangerous! Open
            a window now!
        target:
          entity_id: tts.piper
  mode: single
- id: '1735403018786'
  alias: Presence Activated Office Lights
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.office_multisensor_radar_target
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 3
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: sun
        before: sunrise
        after: sunset
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 50
          kelvin: 4698
        target:
          entity_id: light.office_lamp
    - conditions:
      - condition: sun
        before: sunset
        after: sunrise
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          kelvin: 6014
          brightness_pct: 100
        target:
          entity_id: light.office_lamp
  mode: single
- id: '1735666007028'
  alias: Office - Ikea Remote Actions
  description: ''
  use_blueprint:
    path: jwhb/zigbee2mqtt-ikea-e1524-e1810-tradfri-remote-control.yaml
    input:
      action_sensor: sensor.office_ikea_remote_action
      toggle_action:
      - action: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id:
          - light.office_ceiling
          - light.office_lamp
      brightness_up_action:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 10
        target:
          entity_id:
          - light.office_ceiling
          - light.office_lamp
      brightness_down_action:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: -10
        target:
          entity_id:
          - light.office_ceiling
          - light.office_lamp
      arrow_right_action:
      - action: light.turn_on
        metadata: {}
        data:
          color_temp: '{% set current_temp = state_attr(''light.office_ceiling'',
            ''color_temp'') %} {{ [current_temp - (current_temp * 0.2), 250] | max
            }}

            '
        target:
          entity_id:
          - light.office_ceiling
          - light.office_lamp
      arrow_left_action:
      - action: light.turn_on
        metadata: {}
        data:
          color_temp: '{% set current_temp = state_attr(''light.office_ceiling'',
            ''color_temp'') %} {{ [current_temp + (current_temp * 0.2), 454] | min
            }}

            '
        target:
          entity_id:
          - light.office_ceiling
          - light.office_lamp
- id: '1735999517095'
  alias: Smoke Alarm Notifications
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.smoke_detectors_group
    from: 'off'
    to: 'on'
  conditions: []
  actions:
  - action: notify.mobile_app_kelly_s_iphone_2
    metadata: {}
    data:
      message: Smoke / CO2 Alarm going off at Sussex House
  - action: notify.mobile_app_john_s_iphone
    metadata: {}
    data:
      message: Smoke / CO2 Alarm going off at Sussex House
  mode: single
- id: '1736117206056'
  alias: Living Room - Ikea Remote Actions
  description: ''
  use_blueprint:
    path: jwhb/zigbee2mqtt-ikea-e1524-e1810-tradfri-remote-control.yaml
    input:
      action_sensor: sensor.living_room_ikea_remote_action
      toggle_action:
      - action: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id:
          - light.living_room_lamps
          - light.hanging_light
      brightness_up_action:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 10
        target:
          entity_id:
          - light.living_room_lamps
          - light.hanging_light
      brightness_down_action:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: -10
        target:
          entity_id:
          - light.living_room_lamps
          - light.hanging_light
      arrow_right_action:
      - action: light.turn_on
        metadata: {}
        data:
          color_temp: '{% set current_temp = state_attr(''light.office_ceiling'',
            ''color_temp'') %} {{ [current_temp - (current_temp * 0.2), 250] | max
            }}

            '
        target:
          entity_id:
          - light.living_room_lamps
          - light.hanging_light
      arrow_left_action:
      - action: light.turn_on
        metadata: {}
        data:
          color_temp: '{% set current_temp = state_attr(''light.office_ceiling'',
            ''color_temp'') %} {{ [current_temp + (current_temp * 0.2), 454] | min
            }}

            '
        target:
          entity_id:
          - light.living_room_lamps
          - light.hanging_light
- id: '1736538395203'
  alias: Apollo OTA HA Helper
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_boolean.apollo_ota_mode
    to: 'on'
    for:
      hours: 1
      minutes: 0
      seconds: 0
  conditions: []
  actions:
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.apollo_ota_mode
  mode: single
- id: '1736541306095'
  alias: Publish Ecowitt Data to MQTT
  triggers:
  - minutes: /1
    trigger: time_pattern
  actions:
  - repeat:
      for_each:
      - sensor.ecowitt_weather_station_absolute_pressure
      - sensor.ecowitt_weather_station_daily_rain_rate
      - sensor.ecowitt_weather_station_daily_rain_rate_piezo
      - sensor.ecowitt_weather_station_dewpoint
      - sensor.ecowitt_weather_station_event_rain_rate
      - sensor.ecowitt_weather_station_event_rain_rate_piezo
      - sensor.ecowitt_weather_station_feels_like_temperature
      - sensor.ecowitt_weather_station_hourly_rain_rate
      - sensor.ecowitt_weather_station_hourly_rain_rate_piezo
      - sensor.ecowitt_weather_station_humidity
      - sensor.ecowitt_weather_station_indoor_dewpoint
      - sensor.ecowitt_weather_station_indoor_humidity
      - sensor.ecowitt_weather_station_indoor_temperature
      - sensor.ecowitt_weather_station_max_daily_wind_gust
      - sensor.ecowitt_weather_station_monthly_rain_rate
      - sensor.ecowitt_weather_station_monthly_rain_rate_piezo
      - sensor.ecowitt_weather_station_outdoor_temperature
      - sensor.ecowitt_weather_station_rain_rate
      - sensor.ecowitt_weather_station_rain_rate_piezo
      - sensor.ecowitt_weather_station_relative_pressure
      - sensor.ecowitt_weather_station_solar_lux
      - sensor.ecowitt_weather_station_solar_radiation
      - sensor.ecowitt_weather_station_uv_index
      - sensor.ecowitt_weather_station_weekly_rain_rate
      - sensor.ecowitt_weather_station_weekly_rain_rate_piezo
      - sensor.ecowitt_weather_station_wh90_battery
      - sensor.ecowitt_weather_station_wh90_capacitor
      - sensor.ecowitt_weather_station_wind_direction
      - sensor.ecowitt_weather_station_wind_gust
      - sensor.ecowitt_weather_station_wind_speed
      - sensor.ecowitt_weather_station_windchill
      - sensor.ecowitt_weather_station_yearly_rain_rate
      - sensor.ecowitt_weather_station_yearly_rain_rate_piezo
      - sensor.ecowitt_weather_station_soil_moisture_1
      - sensor.ecowitt_weather_station_soil_ad_1
      - sensor.ecowitt_weather_station_soil_battery_1
      - sensor.ecowitt_weather_station_lightning_strikes
      - sensor.ecowitt_weather_station_last_lightning_strike
      - sensor.ecowitt_weather_station_wh57_battery
      - sensor.ecowitt_weather_station_lightning_strike_distance
      sequence:
      - data:
          topic: '{{ ''wx_station_1/'' + repeat.item.split(''.'')[1] | replace(''ecowitt_weather_station_'',
            '''') }}'
          payload: '{{ states(repeat.item) }}'
          retain: true
        action: mqtt.publish
- id: '1736552170300'
  alias: Publish Ecowitt Data to MQTT (JSON Format)
  description: ''
  triggers:
  - minutes: /1
    trigger: time_pattern
  actions:
  - data:
      topic: wx_station_1_json
      payload: "{\n  \"absolute_pressure\": \"{{ states('sensor.ecowitt_weather_station_absolute_pressure')
        }}\",\n  \"daily_rain_rate\": \"{{ states('sensor.ecowitt_weather_station_daily_rain_rate')
        }}\",\n  \"daily_rain_rate_piezo\": \"{{ states('sensor.ecowitt_weather_station_daily_rain_rate_piezo')
        }}\",\n  \"dewpoint\": \"{{ states('sensor.ecowitt_weather_station_dewpoint')
        }}\",\n  \"event_rain_rate\": \"{{ states('sensor.ecowitt_weather_station_event_rain_rate')
        }}\",\n  \"event_rain_rate_piezo\": \"{{ states('sensor.ecowitt_weather_station_event_rain_rate_piezo')
        }}\",\n  \"feels_like_temperature\": \"{{ states('sensor.ecowitt_weather_station_feels_like_temperature')
        }}\",\n  \"hourly_rain_rate\": \"{{ states('sensor.ecowitt_weather_station_hourly_rain_rate')
        }}\",\n  \"hourly_rain_rate_piezo\": \"{{ states('sensor.ecowitt_weather_station_hourly_rain_rate_piezo')
        }}\",\n  \"humidity\": \"{{ states('sensor.ecowitt_weather_station_humidity')
        }}\",\n  \"indoor_dewpoint\": \"{{ states('sensor.ecowitt_weather_station_indoor_dewpoint')
        }}\",\n  \"indoor_humidity\": \"{{ states('sensor.ecowitt_weather_station_indoor_humidity')
        }}\",\n  \"indoor_temperature\": \"{{ states('sensor.ecowitt_weather_station_indoor_temperature')
        }}\",\n  \"max_daily_wind_gust\": \"{{ states('sensor.ecowitt_weather_station_max_daily_wind_gust')
        }}\",\n  \"monthly_rain_rate\": \"{{ states('sensor.ecowitt_weather_station_monthly_rain_rate')
        }}\",\n  \"monthly_rain_rate_piezo\": \"{{ states('sensor.ecowitt_weather_station_monthly_rain_rate_piezo')
        }}\",\n  \"outdoor_temperature\": \"{{ states('sensor.ecowitt_weather_station_outdoor_temperature')
        }}\",\n  \"rain_rate\": \"{{ states('sensor.ecowitt_weather_station_rain_rate')
        }}\",\n  \"rain_rate_piezo\": \"{{ states('sensor.ecowitt_weather_station_rain_rate_piezo')
        }}\",\n  \"relative_pressure\": \"{{ states('sensor.ecowitt_weather_station_relative_pressure')
        }}\",\n  \"solar_lux\": \"{{ states('sensor.ecowitt_weather_station_solar_lux')
        }}\",\n  \"solar_radiation\": \"{{ states('sensor.ecowitt_weather_station_solar_radiation')
        }}\",\n  \"uv_index\": \"{{ states('sensor.ecowitt_weather_station_uv_index')
        }}\",\n  \"weekly_rain_rate\": \"{{ states('sensor.ecowitt_weather_station_weekly_rain_rate')
        }}\",\n  \"weekly_rain_rate_piezo\": \"{{ states('sensor.ecowitt_weather_station_weekly_rain_rate_piezo')
        }}\",\n  \"wh90_battery\": \"{{ states('sensor.ecowitt_weather_station_wh90_battery')
        }}\",\n  \"wh90_capacitor\": \"{{ states('sensor.ecowitt_weather_station_wh90_capacitor')
        }}\",\n  \"wind_direction\": \"{{ states('sensor.ecowitt_weather_station_wind_direction')
        }}\",\n  \"wind_gust\": \"{{ states('sensor.ecowitt_weather_station_wind_gust')
        }}\",\n  \"wind_speed\": \"{{ states('sensor.ecowitt_weather_station_wind_speed')
        }}\",\n  \"yearly_rain_rate\": \"{{ states('sensor.ecowitt_weather_station_yearly_rain_rate')
        }}\",\n  \"yearly_rain_rate_piezo\": \"{{ states('sensor.ecowitt_weather_station_yearly_rain_rate_piezo')
        }}\",\n  \"soil_moisture_1\": \"{{ states('sensor.ecowitt_weather_station_soil_moisture_1')
        }}\",\n  \"soil_ad_1\": \"{{ states('sensor.ecowitt_weather_station_soil_ad_1')
        }}\",\n  \"soil_battery_1\": \"{{ states('sensor.ecowitt_weather_station_soil_battery_1')
        }}\",\n  \"lightning_strikes\": \"{{ states('sensor.ecowitt_weather_station_lightning_strikes')
        }}\",\n  \"last_lightning_strike\": \"{{ as_timestamp(states('sensor.ecowitt_weather_station_last_lightning_strike'))
        | int }}\",\n  \"lightning_strike_distance\": \"{{ states('sensor.ecowitt_weather_station_lightning_strike_distance')
        }}\"\n}"
      retain: true
    action: mqtt.publish
- id: '1736802576575'
  alias: Purge noisy multisensors
  description: Reduce DB size by purging state changes for specific sensors
  triggers:
  - trigger: time
    at: 00:00:01
  conditions: []
  actions:
  - action: recorder.purge_entities
    metadata: {}
    data:
      keep_days: 7
      entity_globs:
      - sensor.*_radar_still_*
      - sensor.*_radar_move_*
      - sensor.*_radar_*_distance
      - binary_sensor.*_target
      - binary_sensor.*_radar_zone_*_occupancy
      - sensor.*sensor_uptime
      - sensor.*_multisensor_ltr390*
      - sensor.*_rssi
      - sensor.*_uptime
      - sensor.*_esp_temperature
      - sensor.nas_rack_ups_*
      - sensor.cyberpower1500_*
      - sensor.travel_time_*
  mode: single
