- id: '1734040819255'
  alias: Announce Washer is Done
  description: Announce on all Homepods when the washer is done
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.washer_run_completed
    to: 'on'
  conditions:
  - or:
    - condition: zone
      entity_id: person.john
      zone: zone.home
    - condition: zone
      entity_id: person.kelly_barbieri
      zone: zone.home
  actions:
  - action: tts.speak
    metadata: {}
    data:
      cache: true
      media_player_entity_id: media_player.all_pods
      message: Hi there humans! Your washing is done, now its time for the dryer
    target:
      entity_id: tts.home_assistant_cloud
  mode: single
- id: '1734040890462'
  alias: Announce Dryer is Done
  description: Announce on all Homepods when the dryer is done
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.dryer_run_completed
    to: 'on'
  conditions:
  - or:
    - condition: zone
      entity_id: person.john
      zone: zone.home
    - condition: zone
      entity_id: person.kelly_barbieri
      zone: zone.home
  actions:
  - action: tts.speak
    metadata: {}
    data:
      cache: true
      media_player_entity_id: media_player.all_pods
      message: Hi there humans! Your dryer is done, grab those clothes while still
        hot
    target:
      entity_id: tts.home_assistant_cloud
  mode: single
- id: '1735344088242'
  alias: Master Bedroom CO2 Alerting
  description: Master Bedroom CO2 Alerting
  triggers:
  - trigger: state
    entity_id:
    - sensor.bedroom_multisensor_co2
  conditions:
  - condition: or
    conditions:
    - condition: state
      entity_id: person.john
      state: home
    - condition: state
      entity_id: person.kelly_barbieri
      state: home
  actions:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.bedroom_multisensor_co2
        above: 0
        below: 500
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 0
          - 8
          - 255
          brightness_pct: 20
        target:
          entity_id: light.bedroom_multisensor_rgb_light
    - conditions:
      - condition: numeric_state
        entity_id: sensor.bedroom_multisensor_co2
        above: 500
        below: 750
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 37
          - 162
          - 58
          brightness_pct: 25
        target:
          entity_id: light.bedroom_multisensor_rgb_light
    - conditions:
      - condition: numeric_state
        entity_id: sensor.bedroom_multisensor_co2
        above: 750
        below: 1000
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 255
          - 123
          - 0
          brightness_pct: 25
        target:
          entity_id: light.bedroom_multisensor_rgb_light
    - conditions:
      - condition: numeric_state
        entity_id: sensor.bedroom_multisensor_co2
        above: 1000
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 255
          - 0
          - 0
          brightness_pct: 100
          flash: long
        target:
          entity_id: light.bedroom_multisensor_rgb_light
      - action: tts.speak
        metadata: {}
        data:
          cache: true
          media_player_entity_id: media_player.master_bedroom
          message: Warning! The CO2 Level in the Master Bedroom is dangerous! Open
            a window now!
        target:
          entity_id: tts.piper
  mode: single
- id: '1735403018786'
  alias: Presence Activated Office Lights
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.office_multisensor_radar_target
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 3
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: sun
        before: sunrise
        after: sunset
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 50
          kelvin: 4698
        target:
          entity_id: light.office_lamp
    - conditions:
      - condition: sun
        before: sunset
        after: sunrise
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          kelvin: 6014
          brightness_pct: 100
        target:
          entity_id: light.office_lamp
  mode: single
- id: '1735666007028'
  alias: Office - Ikea Remote Actions
  description: ''
  use_blueprint:
    path: jwhb/zigbee2mqtt-ikea-e1524-e1810-tradfri-remote-control.yaml
    input:
      action_sensor: sensor.office_ikea_remote_action
      toggle_action:
      - action: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id:
          - light.office_ceiling
          - light.office_lamp
      brightness_up_action:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 10
        target:
          entity_id:
          - light.office_ceiling
          - light.office_lamp
      brightness_down_action:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: -10
        target:
          entity_id:
          - light.office_ceiling
          - light.office_lamp
      arrow_right_action:
      - action: light.turn_on
        metadata: {}
        data:
          color_temp: '{% set current_temp = state_attr(''light.office_ceiling'',
            ''color_temp'') %} {{ [current_temp - (current_temp * 0.2), 250] | max
            }}

            '
        target:
          entity_id:
          - light.office_ceiling
          - light.office_lamp
      arrow_left_action:
      - action: light.turn_on
        metadata: {}
        data:
          color_temp: '{% set current_temp = state_attr(''light.office_ceiling'',
            ''color_temp'') %} {{ [current_temp + (current_temp * 0.2), 454] | min
            }}

            '
        target:
          entity_id:
          - light.office_ceiling
          - light.office_lamp
- id: '1735999517095'
  alias: Smoke Alarm Notifications
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.smoke_detectors_group
    from: 'off'
    to: 'on'
  conditions: []
  actions:
  - action: notify.mobile_app_kelly_s_iphone_2
    metadata: {}
    data:
      message: Smoke / CO2 Alarm going off at Sussex House
  - action: notify.mobile_app_john_s_iphone
    metadata: {}
    data:
      message: Smoke / CO2 Alarm going off at Sussex House
  mode: single
