- id: '1734040819255'
  alias: Announce Washer is Done
  description: Announce on all Homepods when the washer is done
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.washer_run_completed
    to: 'on'
  conditions:
  - or:
    - condition: zone
      entity_id: person.john
      zone: zone.home
    - condition: zone
      entity_id: person.kelly_barbieri
      zone: zone.home
  actions:
  - action: tts.speak
    metadata: {}
    data:
      cache: true
      media_player_entity_id: media_player.all_pods
      message: Hi there humans! Your washing is done, now its time for the dryer
    target:
      entity_id: tts.home_assistant_cloud
  mode: single
- id: '1734040890462'
  alias: Announce Dryer is Done
  description: Announce on all Homepods when the dryer is done
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.dryer_run_completed
    to: 'on'
  conditions:
  - or:
    - condition: zone
      entity_id: person.john
      zone: zone.home
    - condition: zone
      entity_id: person.kelly_barbieri
      zone: zone.home
  actions:
  - action: tts.speak
    metadata: {}
    data:
      cache: true
      media_player_entity_id: media_player.all_pods
      message: Hi there humans! Your dryer is done, grab those clothes while still
        hot
    target:
      entity_id: tts.home_assistant_cloud
  mode: single
- id: '1735174142072'
  alias: Bedroom CO2 500-600
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.master_bedroom_air_sensor_co2
    for:
      hours: 0
      minutes: 5
      seconds: 0
    above: 500
    below: 600
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      rgb_color:
      - 0
      - 255
      - 0
      brightness_pct: 25
    target:
      entity_id: light.master_bedroom_air_sensor_rgb_light
  mode: single
- id: '1735174363579'
  alias: Bedroom CO2 600-800
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.master_bedroom_air_sensor_co2
    for:
      hours: 0
      minutes: 5
      seconds: 0
    above: 600
    below: 800
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      rgb_color:
      - 247
      - 143
      - 70
      brightness_pct: 25
    target:
      entity_id: light.master_bedroom_air_sensor_rgb_light
  mode: single
- id: '1735174669330'
  alias: Bedroom CO2 800-1000
  description: 'Bedroom '
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.master_bedroom_air_sensor_co2
    for:
      hours: 0
      minutes: 5
      seconds: 0
    above: 800
    below: 1000
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      rgb_color:
      - 234
      - 51
      - 35
      brightness_pct: 25
    target:
      entity_id: light.master_bedroom_air_sensor_rgb_light
  mode: single
