- id: '1734040819255'
  alias: Announce Washer is Done
  description: Announce on all Homepods when the washer is done
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.washer_run_completed
    to: 'on'
  conditions:
  - or:
    - condition: zone
      entity_id: person.john
      zone: zone.home
    - condition: zone
      entity_id: person.kelly_barbieri
      zone: zone.home
  actions:
  - action: tts.speak
    metadata: {}
    data:
      cache: true
      media_player_entity_id: media_player.all_pods
      message: Hi there humans! Your washing is done, now its time for the dryer
    target:
      entity_id: tts.home_assistant_cloud
  mode: single
- id: '1734040890462'
  alias: Announce Dryer is Done
  description: Announce on all Homepods when the dryer is done
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.dryer_run_completed
    to: 'on'
  conditions:
  - or:
    - condition: zone
      entity_id: person.john
      zone: zone.home
    - condition: zone
      entity_id: person.kelly_barbieri
      zone: zone.home
  actions:
  - action: tts.speak
    metadata: {}
    data:
      cache: true
      media_player_entity_id: media_player.all_pods
      message: 'Hi there humans! Your dryer is done, grab those clothes while still
        hot... And DO NOT forget to clean the lint filter Kelly '
    target:
      entity_id: tts.home_assistant_cloud
  mode: single
- id: '1735344088242'
  alias: Master Bedroom CO2 Alerting
  description: Master Bedroom CO2 Alerting
  triggers:
  - trigger: state
    entity_id:
    - sensor.bedroom_multisensor_co2
  conditions:
  - condition: or
    conditions:
    - condition: state
      entity_id: person.john
      state: home
    - condition: state
      entity_id: person.kelly_barbieri
      state: home
  actions:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.bedroom_multisensor_co2
        above: 550
        below: 750
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 37
          - 162
          - 58
          brightness_pct: 25
        target:
          entity_id: light.bedroom_multisensor_rgb_light
    - conditions:
      - condition: numeric_state
        entity_id: sensor.bedroom_multisensor_co2
        above: 750
        below: 1100
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 255
          - 123
          - 0
          brightness_pct: 25
        target:
          entity_id: light.bedroom_multisensor_rgb_light
    - conditions:
      - condition: numeric_state
        entity_id: sensor.bedroom_multisensor_co2
        above: 1100
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 255
          - 0
          - 0
          brightness_pct: 100
          flash: long
        target:
          entity_id: light.bedroom_multisensor_rgb_light
      - action: tts.speak
        metadata: {}
        data:
          cache: true
          media_player_entity_id: media_player.master_bedroom
          message: Warning! The CO2 Level in the Master Bedroom is dangerous! Open
            a window now!
        target:
          entity_id: tts.piper
        enabled: false
  mode: single
- id: '1735403018786'
  alias: Presence Activated Office Lights
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.office_multisensor_radar_target
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 3
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: sun
        before: sunrise
        after: sunset
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 50
          kelvin: 4698
        target:
          entity_id: light.office_lamp
    - conditions:
      - condition: sun
        before: sunset
        after: sunrise
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          kelvin: 6014
          brightness_pct: 100
        target:
          entity_id: light.office_lamp
  mode: single
- id: '1735999517095'
  alias: Smoke Alarm Notifications
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.smoke_detectors_group
    from: 'off'
    to: 'on'
  conditions: []
  actions:
  - action: notify.mobile_app_kelly_s_iphone_2
    metadata: {}
    data:
      message: Smoke / CO2 Alarm going off at Sussex House
  - action: notify.mobile_app_john_s_iphone
    metadata: {}
    data:
      message: Smoke / CO2 Alarm going off at Sussex House
  mode: single
- id: '1736538395203'
  alias: Apollo OTA HA Helper
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_boolean.apollo_ota_mode
    to: 'on'
    for:
      hours: 1
      minutes: 0
      seconds: 0
  conditions: []
  actions:
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.apollo_ota_mode
  mode: single
- id: '1736552170300'
  alias: Publish Ecowitt Data to MQTT (JSON Format)
  description: ''
  triggers:
  - minutes: /1
    trigger: time_pattern
  actions:
  - data:
      topic: wx_station_1_json
      payload: "{\n  \"absolute_pressure\": \"{{ states('sensor.ecowitt_weather_station_absolute_pressure')
        }}\",\n  \"daily_rain_rate\": \"{{ states('sensor.ecowitt_weather_station_daily_rain_rate')
        }}\",\n  \"daily_rain_rate_piezo\": \"{{ states('sensor.ecowitt_weather_station_daily_rain_rate_piezo')
        }}\",\n  \"dewpoint\": \"{{ states('sensor.ecowitt_weather_station_dewpoint')
        }}\",\n  \"event_rain_rate\": \"{{ states('sensor.ecowitt_weather_station_event_rain_rate')
        }}\",\n  \"event_rain_rate_piezo\": \"{{ states('sensor.ecowitt_weather_station_event_rain_rate_piezo')
        }}\",\n  \"feels_like_temperature\": \"{{ states('sensor.ecowitt_weather_station_feels_like_temperature')
        }}\",\n  \"hourly_rain_rate\": \"{{ states('sensor.ecowitt_weather_station_hourly_rain_rate')
        }}\",\n  \"hourly_rain_rate_piezo\": \"{{ states('sensor.ecowitt_weather_station_hourly_rain_rate_piezo')
        }}\",\n  \"humidity\": \"{{ states('sensor.ecowitt_weather_station_humidity')
        }}\",\n  \"indoor_dewpoint\": \"{{ states('sensor.ecowitt_weather_station_indoor_dewpoint')
        }}\",\n  \"indoor_humidity\": \"{{ states('sensor.ecowitt_weather_station_indoor_humidity')
        }}\",\n  \"indoor_temperature\": \"{{ states('sensor.ecowitt_weather_station_indoor_temperature')
        }}\",\n  \"max_daily_wind_gust\": \"{{ states('sensor.ecowitt_weather_station_max_daily_wind_gust')
        }}\",\n  \"monthly_rain_rate\": \"{{ states('sensor.ecowitt_weather_station_monthly_rain_rate')
        }}\",\n  \"monthly_rain_rate_piezo\": \"{{ states('sensor.ecowitt_weather_station_monthly_rain_rate_piezo')
        }}\",\n  \"outdoor_temperature\": \"{{ states('sensor.ecowitt_weather_station_outdoor_temperature')
        }}\",\n  \"rain_rate\": \"{{ states('sensor.ecowitt_weather_station_rain_rate')
        }}\",\n  \"rain_rate_piezo\": \"{{ states('sensor.ecowitt_weather_station_rain_rate_piezo')
        }}\",\n  \"relative_pressure\": \"{{ states('sensor.ecowitt_weather_station_relative_pressure')
        }}\",\n  \"solar_lux\": \"{{ states('sensor.ecowitt_weather_station_solar_lux')
        }}\",\n  \"solar_radiation\": \"{{ states('sensor.ecowitt_weather_station_solar_radiation')
        }}\",\n  \"uv_index\": \"{{ states('sensor.ecowitt_weather_station_uv_index')
        }}\",\n  \"weekly_rain_rate\": \"{{ states('sensor.ecowitt_weather_station_weekly_rain_rate')
        }}\",\n  \"weekly_rain_rate_piezo\": \"{{ states('sensor.ecowitt_weather_station_weekly_rain_rate_piezo')
        }}\",\n  \"wh90_battery\": \"{{ states('sensor.ecowitt_weather_station_wh90_battery')
        }}\",\n  \"wh90_capacitor\": \"{{ states('sensor.ecowitt_weather_station_wh90_capacitor')
        }}\",\n  \"wind_direction\": \"{{ states('sensor.ecowitt_weather_station_wind_direction')
        }}\",\n  \"wind_gust\": \"{{ states('sensor.ecowitt_weather_station_wind_gust')
        }}\",\n  \"wind_speed\": \"{{ states('sensor.ecowitt_weather_station_wind_speed')
        }}\",\n  \"yearly_rain_rate\": \"{{ states('sensor.ecowitt_weather_station_yearly_rain_rate')
        }}\",\n  \"yearly_rain_rate_piezo\": \"{{ states('sensor.ecowitt_weather_station_yearly_rain_rate_piezo')
        }}\",\n  \"soil_moisture_1\": \"{{ states('sensor.ecowitt_weather_station_soil_moisture_1')
        }}\",\n  \"soil_ad_1\": \"{{ states('sensor.ecowitt_weather_station_soil_ad_1')
        }}\",\n  \"soil_battery_1\": \"{{ states('sensor.ecowitt_weather_station_soil_battery_1')
        }}\",\n  \"lightning_strikes\": \"{{ states('sensor.ecowitt_weather_station_lightning_strikes')
        }}\",\n  \"last_lightning_strike\": \"{{ as_timestamp(states('sensor.ecowitt_weather_station_last_lightning_strike'))
        | int }}\",\n  \"lightning_strike_distance\": \"{{ states('sensor.ecowitt_weather_station_lightning_strike_distance')
        }}\",\n  \"timestamp\": \"{{ now().timestamp() }}\"\n}"
      retain: true
    action: mqtt.publish
- id: '1736802576575'
  alias: Purge Noisy Entities
  description: Reduce DB size by purging state changes for specific sensors
  triggers:
  - trigger: time
    at: 00:00:01
  conditions: []
  actions:
  - action: recorder.purge_entities
    metadata: {}
    data:
      keep_days: 7
      entity_globs:
      - sensor.*_radar_still_*
      - sensor.*_radar_move_*
      - sensor.*_radar_*_distance
      - binary_sensor.*_target
      - binary_sensor.*_radar_zone_*_occupancy
      - sensor.*_multisensor_ltr390*
      - sensor.*_uptime
      - sensor.travel_time_*
      - sensor.*_rssi
      - sensor.*_esp_temperature
      - sensor.nas_rack_ups_*
      - sensor.cyberpower1500_*
      - device_tracker.*
      - conversation.*
      - automation.*
      - sensor.*battery*
      - sensor.*wifi*
      - sensor.*iphone*activity*
      - sensor.*iphone*storage*
  - delay:
      minutes: 5
  - action: recorder.purge
    metadata: {}
    data:
      repack: true
  mode: single
- id: '1746056609075'
  alias: Photo Editing Lighting
  description: Editing Photos in Office
  triggers: []
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      xy_color:
      - 0.346
      - 0.3598
      brightness: 255
    target:
      entity_id:
      - light.office_ceiling
      - light.office_lamps
  mode: single
- id: '1746827440111'
  alias: Office Lights Remote Control
  description: ''
  use_blueprint:
    path: chrschorn/z2m2.0_ikea_tradfri_5button_remote_blueprint.yaml
    input:
      remote_device: 3ac7a1ba82299c9f465fe77d247e94a0
      action_toggle:
      - action: light.toggle
        metadata: {}
        data: {}
        target:
          area_id: office
      action_brightness_up_click:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 10
        target:
          area_id: office
      action_brightness_up_hold:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 100
        target:
          area_id: office
      action_brightness_down_click:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: -10
        target:
          area_id: office
      action_brightness_down_hold:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 20
        target:
          area_id: office
      action_arrow_right_click: []
      action_arrow_left_click:
      - action: light.turn_on
        metadata: {}
        data:
          color_temp_kelvin: 2641
        target:
          area_id: office
      action_arrow_right_hold:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 100
          color_temp_kelvin: 5060
        target:
          area_id: office
- id: '1746827991693'
  alias: Guest Room Lighting Remote
  description: ''
  use_blueprint:
    path: chrschorn/z2m2.0_ikea_tradfri_5button_remote_blueprint.yaml
    input:
      remote_device: a53cba8fe79478c890f9ae8494690320
      action_toggle:
      - action: light.toggle
        metadata: {}
        data: {}
        target:
          area_id: guest_bedroom
      action_brightness_up_click:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 10
        target:
          area_id: guest_bedroom
      action_brightness_up_hold:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 100
        target:
          area_id: guest_bedroom
      action_brightness_down_click:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: -10
        target:
          area_id: guest_bedroom
      action_brightness_down_hold:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 20
        target:
          area_id: guest_bedroom
- id: '1746829157932'
  alias: Pilates Studio Lighting Remote
  description: ''
  use_blueprint:
    path: chrschorn/z2m2.0_ikea_tradfri_5button_remote_blueprint.yaml
    input:
      remote_device: f748043323f5ba81019679fde4e97c91
      action_toggle:
      - action: light.toggle
        metadata: {}
        data: {}
        target:
          area_id: pilates_studio
      action_brightness_up_click:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 10
        target:
          area_id: pilates_studio
      action_brightness_up_hold:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 100
        target:
          area_id: pilates_studio
      action_brightness_down_click:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: -10
        target:
          area_id: pilates_studio
      action_brightness_down_hold:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 20
        target:
          area_id: pilates_studio
- id: '1746893622188'
  alias: Living Room Lights Remote Control
  description: Control Lights in the Living Room (No Ceiling Lights)
  use_blueprint:
    path: chrschorn/z2m2.0_ikea_tradfri_5button_remote_blueprint.yaml
    input:
      remote_device: 9ba52218b8a7670b664616c1b5f25850
      action_toggle:
      - action: light.toggle
        metadata: {}
        data:
          brightness_pct: 35
        target:
          entity_id:
          - light.living_room_lamps
          - light.hanging_light
      action_brightness_up_click:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 10
        target:
          entity_id:
          - light.living_room_lamps
          - light.hanging_light
      action_brightness_up_hold:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 100
        target:
          entity_id:
          - light.living_room_lamps
          - light.hanging_light
      action_brightness_down_click:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: -10
        target:
          entity_id:
          - light.living_room_lamps
          - light.hanging_light
      action_brightness_down_hold:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 30
        target:
          entity_id:
          - light.living_room_lamps
          - light.hanging_light
      action_arrow_right_click: []
      action_arrow_left_click:
      - action: light.turn_on
        metadata: {}
        data:
          color_temp_kelvin: 2641
        target:
          entity_id:
          - light.living_room_lamps
          - light.hanging_light
      action_arrow_right_hold:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 100
          color_temp_kelvin: 5060
        target:
          entity_id:
          - light.living_room_lamps
          - light.hanging_light
- id: '1746972753494'
  alias: Basement Lights Remote Control
  description: ''
  use_blueprint:
    path: chrschorn/z2m2.0_ikea_tradfri_5button_remote_blueprint.yaml
    input:
      remote_device: 092b4b399a67a141a2284315e9fcfd75
      action_toggle:
      - action: light.toggle
        metadata: {}
        data:
          brightness_pct: 100
        target:
          entity_id: light.basement_lights
          device_id: 92a1680a0d126d0363ef681438c34046
- id: '1747869631270'
  alias: Back Yard - Collect Bird Buddy Postcard
  description: Collect Bird Buddy Postcards automation
  use_blueprint:
    path: jhansche/collect_postcard.yaml
    input:
      feeder_device: 8584d5c254e7cd42845e07b845a36599
      share_media: false
- id: '1748042668343'
  alias: MC Cartridge Notification
  description: ''
  triggers:
  - entity_id: sensor.canon_pro_1100_series_mc
    above: 80
    trigger: numeric_state
  actions:
  - data:
      title: Canon Pro-1100 Maintenance Cartridge
      message: MC-20 is 80% full — order a replacement before it halts printing!
    action: notify.mobile_app_john_s_iphone
- id: '1757774013120'
  alias: Front Porch and Garage Lights - Lux Based Control
  description: Simple fade in/out based on darkness
  triggers:
  - entity_id: sensor.ecowitt_weather_station_solar_lux
    below: 500
    for:
      minutes: 5
    id: lights_on
    trigger: numeric_state
  - entity_id: sensor.ecowitt_weather_station_solar_lux
    above: 2500
    for:
      minutes: 5
    id: lights_off
    trigger: numeric_state
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id: lights_on
      sequence:
      - target:
          entity_id:
          - light.porch_light
          - light.garage_front_light
        data:
          brightness: 255
          kelvin: 3000
          transition: 30
        action: light.turn_on
    - conditions:
      - condition: trigger
        id: lights_off
      sequence:
      - target:
          entity_id:
          - light.porch_light
          - light.garage_front_light
        data:
          transition: 60
        action: light.turn_off
  mode: single
