- id: '1734040819255'
  alias: Announce Washer is Done
  description: Announce on all Homepods when the washer is done
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.washer_run_completed
    to: 'on'
  conditions:
  - or:
    - condition: zone
      entity_id: person.john
      zone: zone.home
    - condition: zone
      entity_id: person.kelly_barbieri
      zone: zone.home
  actions:
  - action: tts.speak
    metadata: {}
    data:
      cache: true
      media_player_entity_id: media_player.all_pods
      message: Hi there humans! Your washing is done, now its time for the dryer
    target:
      entity_id: tts.home_assistant_cloud
  mode: single
- id: '1734040890462'
  alias: Announce Dryer is Done
  description: Announce on all Homepods when the dryer is done
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.dryer_run_completed
    to: 'on'
  conditions:
  - or:
    - condition: zone
      entity_id: person.john
      zone: zone.home
    - condition: zone
      entity_id: person.kelly_barbieri
      zone: zone.home
  actions:
  - action: tts.speak
    metadata: {}
    data:
      cache: true
      media_player_entity_id: media_player.all_pods
      message: Hi there humans! Your dryer is done, grab those clothes while still
        hot
    target:
      entity_id: tts.home_assistant_cloud
  mode: single
- id: '1735344088242'
  alias: Master Bedroom CO2 Alerting
  description: Master Bedroom CO2 Alerting
  triggers:
  - trigger: state
    entity_id:
    - sensor.bedroom_multisensor_co2
  conditions:
  - condition: or
    conditions:
    - condition: state
      entity_id: person.john
      state: home
    - condition: state
      entity_id: person.kelly_barbieri
      state: home
  actions:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.bedroom_multisensor_co2
        above: 0
        below: 500
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 0
          - 8
          - 255
          brightness_pct: 20
        target:
          entity_id: light.bedroom_multisensor_rgb_light
    - conditions:
      - condition: numeric_state
        entity_id: sensor.bedroom_multisensor_co2
        above: 500
        below: 750
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 37
          - 162
          - 58
          brightness_pct: 25
        target:
          entity_id: light.bedroom_multisensor_rgb_light
    - conditions:
      - condition: numeric_state
        entity_id: sensor.bedroom_multisensor_co2
        above: 750
        below: 1000
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 255
          - 123
          - 0
          brightness_pct: 25
        target:
          entity_id: light.bedroom_multisensor_rgb_light
    - conditions:
      - condition: numeric_state
        entity_id: sensor.bedroom_multisensor_co2
        above: 1000
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 255
          - 0
          - 0
          brightness_pct: 100
          flash: long
        target:
          entity_id: light.bedroom_multisensor_rgb_light
      - action: tts.speak
        metadata: {}
        data:
          cache: true
          media_player_entity_id: media_player.master_bedroom
          message: Warning! The CO2 Level in the Master Bedroom is dangerous! Open
            a window now!
        target:
          entity_id: tts.piper
  mode: single
- id: '1735403018786'
  alias: Presence Activated Office Lights
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.office_multisensor_radar_target
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 3
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: sun
        before: sunrise
        after: sunset
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 50
          kelvin: 4698
        target:
          entity_id: light.office_lamp
    - conditions:
      - condition: sun
        before: sunset
        after: sunrise
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          kelvin: 6014
          brightness_pct: 100
        target:
          entity_id: light.office_lamp
  mode: single
- id: '1735424330301'
  alias: Hue Dimmer Actions
  description: ''
  use_blueprint:
    path: CrazyCoder/zigbee2mqtt_hue_dimmer_v2.yaml
    input:
      helper_last_controller_event: input_text.hue_dimmer_last_controller_event
      action_sensor: sensor.hue_dimmer_switch_action
      on_press:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 100
          kelvin: 5000
        target:
          entity_id:
          - light.office_ceiling
          - light.office_lamp
      up_press:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 10
        target:
          entity_id:
          - light.office_ceiling
          - light.office_lamp
      down_press:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: -10
        target:
          entity_id:
          - light.office_ceiling
          - light.office_lamp
      off_press:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id:
          - light.office_ceiling
          - light.office_lamp
      on_hold_once: []
      up_hold: []
