- id: '1734040819255'
  alias: Announce Washer is Done
  description: Announce on all Homepods when the washer is done
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.washer_run_completed
    to: 'on'
  conditions:
  - or:
    - condition: zone
      entity_id: person.john
      zone: zone.home
    - condition: zone
      entity_id: person.kelly_barbieri
      zone: zone.home
  actions:
  - action: tts.speak
    metadata: {}
    data:
      cache: true
      media_player_entity_id: media_player.all_pods
      message: Hi there humans! Your washing is done, now its time for the dryer
    target:
      entity_id: tts.home_assistant_cloud
  mode: single
- id: '1734040890462'
  alias: Announce Dryer is Done
  description: Announce on all Homepods when the dryer is done
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.dryer_run_completed
    to: 'on'
  conditions:
  - or:
    - condition: zone
      entity_id: person.john
      zone: zone.home
    - condition: zone
      entity_id: person.kelly_barbieri
      zone: zone.home
  actions:
  - action: tts.speak
    metadata: {}
    data:
      cache: true
      media_player_entity_id: media_player.all_pods
      message: Hi there humans! Your dryer is done, grab those clothes while still
        hot
    target:
      entity_id: tts.home_assistant_cloud
  mode: single
- id: '1735344088242'
  alias: Master Bedroom CO2 Alerting
  description: Master Bedroom CO2 Alerting
  triggers:
  - trigger: state
    entity_id:
    - sensor.master_bedroom_air_sensor_co2
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.master_bedroom_air_sensor_co2
        above: 0
        below: 500
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 0
          - 8
          - 255
          brightness_pct: 15
        target:
          entity_id: light.master_bedroom_air_sensor_rgb_light
    - conditions:
      - condition: numeric_state
        entity_id: sensor.master_bedroom_air_sensor_co2
        above: 500
        below: 750
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 37
          - 162
          - 58
          brightness_pct: 15
        target:
          entity_id: light.master_bedroom_air_sensor_rgb_light
    - conditions:
      - condition: numeric_state
        entity_id: sensor.master_bedroom_air_sensor_co2
        above: 750
        below: 1000
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 255
          - 123
          - 0
          brightness_pct: 15
        target:
          entity_id: light.master_bedroom_air_sensor_rgb_light
    - conditions:
      - condition: numeric_state
        entity_id: sensor.master_bedroom_air_sensor_co2
        above: 1000
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          rgb_color:
          - 255
          - 0
          - 0
          brightness_pct: 100
          flash: long
        target:
          entity_id: light.master_bedroom_air_sensor_rgb_light
      - action: tts.speak
        metadata: {}
        data:
          cache: true
          media_player_entity_id: media_player.master_bedroom
          message: Warning! The CO2 Level in the Master Bedroom is dangerous! Open
            a window now!
        target:
          entity_id: tts.piper
  mode: single
