substitutions:
  name: plant-sensor-01
  friendly_name: Plant Sensor 01
packages:
  ApolloAutomation.PLT-1B: github://ApolloAutomation/PLT-1/Integrations/ESPHome/PLT-1B_Minimal.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret api_key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
