substitutions:
  name: bedroom-voice-assistant
  friendly_name: Bedroom Voice Assistant
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret api_key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
