substitutions:
  name: esp32-s3-box-3-5acb94
  friendly_name: Voice Assist
packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: e8/yVVSLKt60EYOLM//FB0TkfW2Qlx4N3MMnRzR1vas=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
