esphome:
  name: weatherboard
  friendly_name: WeatherBoard

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "2MD9V/JCmKLKyHGrJkvFaBlfKA7fhiTYJuyLboqTlwc="

ota:
  - platform: esphome
    password: "be778ef5f217f4187d35d854d599e697"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Weatherboard Fallback Hotspot"
    password: "WmrNCQhHmOPN"

captive_portal:
    