substitutions:
  name: apollo-plt-1b-2add78
  friendly_name: Plant Sensor 01
packages:
  ApolloAutomation.PLT-1B_Minimal: github://ApolloAutomation/PLT-1/Integrations/ESPHome/PLT-1B_Minimal.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: dU7UWtDYg0drM+a63zJfUULIUZKVlPs5oR5EqlQs3Is=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
