substitutions:
  name: bedroom-multi-sensor
  friendly_name: Bedroom Multi Sensor
packages:
  ApolloAutomation.MSR-1: github://ApolloAutomation/MSR-1/Integrations/ESPHome/MSR-1.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret api_key

logger:
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
