substitutions:
  name: esp32-box-3-testing
  friendly_name: ESO S3 Box 3 - Testing
packages:
  esphome.voice-assistant: github://esphome/firmware/voice-assistant/esp32-s3-box-3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret api_key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
